### ISSUE TITLE
Support M1 & Intel Mac

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/telos-evm-docker#99]

**Comment by Dewald928** [comment]
We have experience with this. Let us know if you need help.

**Comment by Dewald928** [comment]
I'll create a gist and share it, don't know if it entirely solves your issue. But we do have leap running on M1

**Comment by guilledk** [comment]
Yeah we could run on mac with other configurations, not when starting from genesis tho

**Comment by guilledk** [comment]
@poplexity found that if you disable `OC` mode it works, in `tevmc.json` this can be done at:

`config['nodeos']['ini']['vm_oc_enable'] = false`
